# Generated by Django 5.2.4 on 2025-07-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
