# Generated by Django 5.2.4 on 2025-07-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='win_rule',
            field=models.CharField(choices=[('min', 'Smaller number wins'), ('max', 'Larger number wins')], default='min', max_length=3),
        ),
    ]
